Implement Lab6 Feature
anz-bank/go-course pull request #100
Opened 2019-02-14 09:12 UTC by jatheesh

Fixes #88 

#### Changes proposed in this PR:
LAB 6 Implementation
-Add Sorter interface with CRUD for Puppy Struct
-Add implementations for map and Sync.Map as two Stores
-Add associated test cases.

2019-02-14 09:32 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Create(string, string, string) Puppy
Addressed by using in the Main method

2019-02-14 09:33 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Update(Puppy) int
Addressed by using in the Main method

2019-02-14 09:33 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Delete(Puppy) int
Addressed by using in the Main method

2019-02-14 09:33 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	pup, _ := store.m[id]
Corrected

2019-02-14 09:33 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Read(int) Puppy
Addressed by using in the Main method

2019-02-14 09:33 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Initialize()
Addressed by using in the Main method

2019-02-14 09:34 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +	Id     int
Addressed

2019-02-14 09:34 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +type Storer interface {
Addressed by using in the Main method

2019-02-14 09:34 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD.go
> +type Initializer interface {
Addressed by using in the Main method

2019-02-14 09:38 UTC, jatheesh commented on 06_puppy/Jat/puppyCRUD_test.go
> +	npup.Value = "Mike"
Addressed

2019-02-14 13:38 UTC, juliaogris commented
Please fix broken build.

2019-02-15 02:57 UTC, juliaogris requested changes
Looks pretty good!

I suggest breaking up the code into a few more files and adding the test-suite-test-against-interface approach.

2019-02-15 02:57 UTC, juliaogris commented on 06_puppy/Jat/puppyCRUD.go
> +func (store *MapStore) Initialize() {
A more go-idiomatic way would be to have constructor/factory type function prefixed with `New`:
```go
func NewMapStore() *MapStore {
    return &MapStore{m: map[int]Puppy{}}
}
```
but this is fine too.

2019-02-15 02:57 UTC, juliaogris commented on 06_puppy/Jat/puppyCRUD.go
> +func (store *MapStore) Create(breed string, colour string, value string) Puppy {
👍 No confusion about IDs here.

2019-02-15 02:57 UTC, juliaogris commented on 06_puppy/Jat/puppyCRUD.go
> +//Map Store
Consider separating your code up into the following files:
- `storer.go` or `types.go` containing storer interface and Puppy
- `mapstore.go`
- `syncstore.go`
- `main.gop`

2019-03-10 10:38 UTC, juliaogris commented
Hi,
There has been  no activity in the last 20 days so I will close this PR.
Feel free to open it again if you have something to add.
Thanks!
Julia

2019-03-10 10:38 UTC, closed without merging