Lab 06 - Program for CRUD operations on puppy struct
anz-bank/go-course pull request #115
Opened 2019-02-27 06:14 UTC by jecofang01

Fixes #88 

#### Changes proposed in this PR:

* Implement stringer
* Customize the error and error handling
* Implement CRUD operations
* Add test case

2019-03-03 03:01 UTC, anzdaddy requested changes

2019-03-03 03:01 UTC, anzdaddy commented on 06_puppy/jecofang/main.go
> +	if err := ms.Create(p1); err == nil {
These tests look to be the wrong way around. You should test for `err != nil` and exit with an error if so. You might also want to move this into a `main2` in order to have a single block of code in `main` that checks for and reports any errors.

2019-03-03 03:01 UTC, anzdaddy commented on 06_puppy/jecofang/main.go
> +	if err := ms.Create(p1); err == nil {
Alternatively, it looks like `main` is really just intended to test the library. If so, you should just rework (and rename) `TestMainOutput` to be self-contained and not have a `main` at all (though this might not strictly conform to the Lab 6 requirements).

2019-03-03 03:01 UTC, anzdaddy commented on go.sum
> +github.com/fsnotify/fsnotify v1.4.7/go.mod h1:jwhsz4b93w/PPRr/qN1Yymfu8t87LnFCMoQvtojpjFo=
Create your own module under `06_puppy/jecofang`.

2019-03-03 03:01 UTC, anzdaddy commented on go.mod
> +require (
Create your own module under `06_puppy/jecofang`.

2019-04-30 05:07 UTC, juliaogris commented
Sorry, I will close this PR now in preparation for the next training in a few weeks in Melbourne - feel free to re-open it if you want to continue work on it.

2019-04-30 05:07 UTC, closed without merging