Lab 02 - Sort algorithm implementation
anz-bank/go-course pull request #116
Opened 2019-02-27 07:50 UTC by JackLeeHal

* Implement bubble sort
* Implement heap sort
* Add test cases

Fixes #

#### Changes proposed in this PR:

-
-

2019-03-03 03:13 UTC, anzdaddy requested changes

2019-03-03 03:13 UTC, anzdaddy commented on 02_bubble/jacklee/main.go
> +		for j := 0; j < arrLen-1-i; j++ {
If `i` counts down, you can simplify `j`'s loop. https://github.com/anz-bank/go-training/pull/114#discussion_r261849435

2019-03-03 03:13 UTC, anzdaddy commented on 02_bubble/jacklee/main.go
> +		n := len(heap)
Move this to the top of the loop and use it when calling `swap` and `down`.

2019-03-03 03:13 UTC, anzdaddy commented on 02_bubble/jacklee/main.go
> +	for i := n/2 - 1; i >= 0; i-- {
It feels like this should be `(n - 1)/2`. I could be wrong, though. I haven't drilled down to check.

2019-03-03 03:13 UTC, anzdaddy commented on 02_bubble/jacklee/main.go
> +func less(a, b int, heap []int) bool {
I think this complicates things unnecessarily. `!(heap[j1] < heap[j2])` (or `heap[j1] >= heap[j2]`) is more straightforward.

2019-03-03 03:13 UTC, anzdaddy commented on 02_bubble/jacklee/main_test.go
> +}{
This one is largely a matter of personal preference, but in this case I would prefer a one-liner:
```go
var testCases = []struct{in, out []int}{
	…
}
```

2019-04-30 05:07 UTC, juliaogris commented
Sorry, I will close this PR now in preparation for the next training in a few weeks in Melbourne - feel free to re-open it if you want to continue work on it.

2019-04-30 05:07 UTC, closed without merging