Lab 04 - Implement numeronym
anz-bank/go-course pull request #120
Opened 2019-03-01 02:29 UTC by JackLeeHal

Fixes #67

#### Changes proposed in this PR:

* Implement the numeronym
* Add test cases

2019-03-06 15:05 UTC, mohankrishna requested changes
Looks good overall except few small changes.

2019-03-06 15:05 UTC, mohankrishna commented on 04_numeronym/jacklee/numeronym.go
> +		if len(val) < 4 {
`len(val)` is used at multiple places, it is good to assign it to a variable and use the variable where required.

2019-03-06 15:05 UTC, mohankrishna commented on 04_numeronym/jacklee/numeronyms_test.go
> +		l := v.in
I would suggest getting the actual output from `numeronyms` here and comparing it with the expected value in the next line.

```go
//When
actual := numeronyms(v.in...)

//Then
require.Equal(t, v.expected, actual, "Unexpected output in numeronyms()")
```

2019-03-06 15:05 UTC, mohankrishna commented on 04_numeronym/jacklee/numeronym.go
> +		var val = []rune(strings.Trim(v, "\n "))
You can update this to trim the tab character as well by changing it to

```go 
var val = []rune(strings.Trim(v, "\n\t "))
```
or you can also use `strings.TrimSpace()` which trims \n, \t and spaces

```go 
var val = []rune(strings.TrimSpace(v))
```

https://play.golang.org/p/WlMT1CQepia

2019-04-30 05:07 UTC, juliaogris commented
Sorry, I will close this PR now in preparation for the next training in a few weeks in Melbourne - feel free to re-open it if you want to continue work on it.

2019-04-30 05:07 UTC, closed without merging