Lab 1 - Fibonacci and Negafibonacci
anz-bank/go-course pull request #130
Opened 2019-05-20 02:53 UTC by kasunfdo

Fixes #24 

#### Changes proposed in this PR:
* Implement Fibonacci and Negafibonacci series
* Add unit tests

2019-05-20 12:17 UTC, marcelocantos commented on 01_fib/kasunfdo/main.go
> +		_, _ = fmt.Fprintln(out, 0)
No need for assignment.

2019-05-20 12:17 UTC, marcelocantos commented on 01_fib/kasunfdo/main.go
> +	n2 := sign
`n1, n2 := 1, sign` (to match the assignment inside the loop)

2019-05-20 12:17 UTC, marcelocantos commented on 01_fib/kasunfdo/main.go
> +		_, _ = fmt.Fprintln(out, n1)
No need for assignment.

2019-05-20 12:17 UTC, marcelocantos commented on 01_fib/kasunfdo/main_test.go
> +	fmt.Println(expected != actual)
Don't print in tests unless there's a problem.

2019-05-20 12:17 UTC, marcelocantos commented on 01_fib/kasunfdo/main_test.go
> +		t.Errorf("Unexpected output in main()")
Print full context here. Something like:
```go
t.Errorf("Unexpected output in main()\nexpected: %q\nactual: %q", expected, actual)
```

2019-05-27 08:24 UTC, n0npax submitted a review, later dismissed
LGTM

2019-05-27 23:09 UTC, kasunfdo commented
Rebased with latest master branch

2019-05-28 23:11 UTC, juliaogris requested changes
This might be a bit nit-picky - over all this PR looks pretty perfect to me, but seeing as you are the first one to submit it: Most of these tests here do exactly the same thing, so use Table Driven tests instead (maps as data structure and `t.Run(...)` as described in recent [Dave Cheney post](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) at the bottom: "Introducing sub tests").

2019-05-30 02:11 UTC, kasunfdo commented
Thank you @juliaogris for guidance. I updated the PR.

2019-05-30 03:20 UTC, juliaogris approved these changes
LGTM!

You have done a lot more than was asked of you - respect!

Nonetheless, for future labs your table driven tests would look even nicer if you used something similar to this [sample code](https://github.com/anz-bank/go-slides/blob/master/samples/testing/basic/cases_test.go#L14) - see how it uses `t.Run` and a `map` for the actual test cases? This will print test cases nicer and make it easier to debug in case of failure (also described in the bottom section of the [Dave Cheney post](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests)).

2019-05-30 03:24 UTC, kasunfdo commented
Noted. Thanks

2019-05-30 03:27 UTC, merged