Lab 2 - Bubble sort
anz-bank/go-course pull request #132
Opened 2019-05-20 23:24 UTC by kasunfdo

Fixes #42

#### Changes proposed in this PR:
* Implement bubble sort
* Implement insertion sort
* Implement merge sort

2019-05-30 02:11 UTC, juliaogris requested changes
Great work @kasunfdo ! Same [comments](https://github.com/anz-bank/go-course/pull/134#pullrequestreview-243597281) as from Lab4 PR apply.

2019-05-30 20:50 UTC, juliaogris requested changes
Nice work!
Please add whose other PR you have reviewed as link to the PR description.
Test some corner cases (empty array, single element array, already sorted array, array in reverse order). You can probably use Table driven tests for this too.

2019-05-31 12:19 UTC, jonathanheaden requested changes

2019-05-31 12:19 UTC, jonathanheaden commented on 02_bubble/kasunfdo/main.go
> +	out := make([]int, len(s))
Why is it needed to create a new slice?

2019-05-31 12:19 UTC, jonathanheaden commented on 02_bubble/kasunfdo/main.go
> +	out := make([]int, len(input))
Is the new slice needed?

2019-06-02 22:45 UTC, jonathanheaden commented on 02_bubble/kasunfdo/main.go
> +	out := make([]int, len(s))
I see now that it is needed to prevent mutating the original slice

2019-06-02 22:45 UTC, jonathanheaden commented on 02_bubble/kasunfdo/main.go
> +	out := make([]int, len(input))
I see now that it is needed to prevent mutating the original slice

2019-06-02 22:46 UTC, jonathanheaden approved these changes
looks good

2019-06-03 03:02 UTC, juliaogris approved these changes
LGTM - great work!

2019-06-03 22:52 UTC, merged