Lab2
anz-bank/go-course pull request #186
Opened 2019-05-31 00:47 UTC by shampa077

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-05-31 00:52 UTC, eastrd requested changes
- Consider using table driven tests to avoid repetition ([Dave Cheney post](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests))

2019-05-31 03:15 UTC, shampa077 commented
Changes done requested by @eastrd

2019-05-31 03:21 UTC, eastrd reviewed
LGTM

2019-06-04 03:52 UTC, juliaogris requested changes
Please read through the [Collected Code Review Comments](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments)

- [Fix your pr description](https://github.com/anz-bank/go-course/wiki/Lab-2:-Collected-Code-Review-Comments#pr-description)
- [Limit the number of commits to one or two](https://github.com/anz-bank/go-course/wiki/Lab-2:-Collected-Code-Review-Comments#limit-the-number-of-commits-to-one-or-two)
- Undo the removal of directory `01_fib/kasunfdo`

2019-06-16 07:45 UTC, pentaphobe requested changes
Hi @shampa077 looking good, thanks for resolving (most of) the issues @juliaogris mentioned.

However:

- please don't forget to rebase so you're still within 2 commits!  https://github.com/anz-bank/go-course/wiki/Lab-2:-Collected-Code-Review-Comments#limit-the-number-of-commits-to-one-or-two
- please include a reference to a review of a colleague's PR in your description

2020-02-08 02:58 UTC, juliaogris commented
The go-course is now closed. Thank you very much for participating.

2020-02-08 02:58 UTC, closed without merging