lab4 numeronym
anz-bank/go-course pull request #217
Opened 2019-06-02 07:13 UTC by shuutech

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-06-03 03:18 UTC, pentaphobe requested changes
Please review the [Code Review Comments](https://github.com/anz-bank/go-course/wiki/Lab-4:-Collected-Code-Review-Comments) and update your PR accordingly

Particularly:

- [Include a description in your PR](https://github.com/anz-bank/go-course/wiki/Lab-4:-Collected-Code-Review-Comments#pr-description)
- [Commit message style](https://github.com/anz-bank/go-course/wiki/Lab-4:-Collected-Code-Review-Comments#commit-messages)

Note that most of that list's procedures apply to _all_ lab Pull Requests, and should ideally be done in all your projects until they become second nature.


Keep it up!

2019-06-09 11:50 UTC, Joshcarp commented
Remove binary files,
Also try running `golangci-lint run` before you push

2019-06-26 09:53 UTC, pentaphobe commented
One more thing, please also include a reference to your review of a colleague's PR

2020-02-08 03:03 UTC, juliaogris commented
The go-course is now closed. Thank you very much for participating.

2020-02-08 03:03 UTC, closed without merging