lab 5 stringer
anz-bank/go-course pull request #220
Opened 2019-06-02 09:12 UTC by shuutech

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-06-09 11:23 UTC, kasunfdo requested changes
Implementation is OK, but testing should be improved.
Consider following.

- Uninitialized IPAddr(`IPAddr{}`)
- Semi-initialized IP Addr(`IPAddr{127,23}`)

2019-06-09 11:23 UTC, kasunfdo commented on 05_stringer/shuutech/main.go
> +	ip := fmt.Sprintf("%d.%d.%d.%d", ipAddress[0], ipAddress[1], ipAddress[2], ipAddress[3])
Return directly without using a variable

2019-06-09 11:23 UTC, kasunfdo commented on 05_stringer/shuutech/main_test.go
> +func TestMain(m *testing.M) {
This test will never fail. 

You can make main function testable using following printf method.
`fmt.Fprintln(out, IPAddr{127, 0, 0, 1})`

2019-06-09 11:23 UTC, kasunfdo commented on 05_stringer/shuutech/main_test.go
> +	expected = "127.0.0.1"
Declare and assign directly as follows.
`expected := = "127.0.0.1"`

2020-02-08 02:57 UTC, juliaogris commented
The go-course is now closed. Thank you very much for participating.

2020-02-08 02:57 UTC, closed without merging