completed lab 5
anz-bank/go-course pull request #284
Opened 2019-06-06 11:00 UTC by luliangLi

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:
- Complete lab 5 Stringers
- Test Stringers

2019-06-06 12:54 UTC, n0npax approved these changes
LGTM

2019-06-09 11:34 UTC, Joshcarp commented
@luliangLi Any reason why this looks almost identical to @n0npax lab5?

2019-06-11 00:26 UTC, juliaogris requested changes
We strongly encourage that you complete these labs on your own and don't copy them from others.   
Copying labs creates unnecessary effort on our side and limited learning on your side.

We don't know whether your solution coincidentally looks like #215 by @n0npax  (apologies!!), whether you have collaborated (acceptable, please clarify in PR description) or whether you have copied these lines (discouraged, please try again on your own). Just let us know what happened.

Thanks for your understanding.

2019-06-11 00:26 UTC, juliaogris commented on 05_stringer/luliangLi/main_test.go
> +func TestStringify(t *testing.T) {
See @n0npax's  [`TestStringify`](https://github.com/anz-bank/go-course/pull/215/files#diff-333f80df5d7b211e6addaa175bd579d7R25)

2019-06-11 00:26 UTC, juliaogris commented on 05_stringer/luliangLi/main_test.go
> +		t.Errorf("Unexpected output. Expected: %q - Actual: %q", expected, actual)
Identically error message to @n0npax's [`t.Errorf`](https://github.com/anz-bank/go-course/pull/215/files#diff-333f80df5d7b211e6addaa175bd579d7R21)

2019-06-12 02:19 UTC, luliangLi commented
> @luliangLi Any reason why this looks almost identical to @n0npax lab5?
@juliaogris @Joshcarp Hi, sorry for confusing you guys. I actually got the idea from the following stackoverflow: https://stackoverflow.com/questions/50568424/convert-a-byte-array-to-a-string-array, which is almost the same with the solution from @n0npax, which is coincidental I think.
For test cases file I actually copied from his, originally I would like to copy from my previous labs but it needed to switch git branches...

2020-02-08 02:57 UTC, juliaogris commented
The go-course is now closed. Thank you very much for participating.

2020-02-08 02:57 UTC, closed without merging