Complete lab 1 fibonnaci
anz-bank/go-course pull request #379
Opened 2019-06-14 00:57 UTC by leonarj4

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-06-14 09:59 UTC, davidbroughsmyth commented
Suggest you run gofmt and golangci-lint before submitting your PR
gofmt -s -w .
golangci-lint run

2019-06-14 10:19 UTC, davidbroughsmyth commented on 01_fib/leonarj4/main.go
> +func main() {
The lab calls for calling fib(7) in main. The printing is done in the fib(n) function and does not return the final Fibonacci number but the whole sequence. So as fib(1) would just print 1, fib(3) would be
 1
 1
 2

2019-07-05 05:47 UTC, krnicolson requested changes
A little reorganising of this code is required to fulfil the brief

2019-07-05 05:47 UTC, krnicolson commented on 01_fib/leonarj4/main.go
> +import ("fmt")
You should be able to configure your IDE to run gofmt/goimports for you. Have a look into it and it'll save you forgetting in future PRs

2019-07-05 05:47 UTC, krnicolson commented on 01_fib/leonarj4/main_test.go
> +		}
You are only testing your fib() function here but you should also test your main function. 
I also agree with comment above - that you should implement fib() and main() as described in the lab spec.

2020-02-08 03:02 UTC, juliaogris commented
The go-course is now closed. Thank you very much for participating.

2020-02-08 03:02 UTC, closed without merging