Created IPAddr data type
anz-bank/go-course pull request #394
Opened 2019-06-16 04:30 UTC by joel00wood

Overwrote `.String()` implementation to output underlying byte slice `{0,0,0,0}` as \'0.0.0.0\'

Fixes  #393

Review of colleague's PR #

#### Changes proposed in this PR:
- IPAddr data type
- Overwrites underlying `.String()` to format output as an IP v4 Address

2019-06-17 08:26 UTC, n0npax requested changes

2019-06-17 08:26 UTC, n0npax commented on 05_stringer/joel00wood/main_test.go
> +	}
please add test for empty and half-initialized `IPAddr` I mean `IPAddr{}` and `IPAddr{10.10}`

2019-06-17 08:26 UTC, n0npax commented on 05_stringer/joel00wood/main_test.go
> +func captureOutput(f func()) string {
same as: https://github.com/anz-bank/go-course/pull/359 - this is an overkill

2019-06-24 11:28 UTC, joel00wood commented on 05_stringer/joel00wood/main_test.go
> +	}
Implemented as described, thanks for pointing this out!

2019-06-24 11:29 UTC, joel00wood commented on 05_stringer/joel00wood/main_test.go
> +func captureOutput(f func()) string {
I still partially agree but continue to find it fit for purpose

2019-06-24 11:35 UTC, joel00wood commented
@n0npax Implemented changes where appropriate, please re-review when able :D

2019-06-26 00:43 UTC, n0npax requested changes

2019-06-26 00:43 UTC, n0npax commented on 05_stringer/joel00wood/main_test.go
> +	if expected != actual {
please use testify instead of raw comparisions.
Sorry I missed this during 1st review.
Rest is fine!

2019-06-26 01:03 UTC, n0npax submitted a review, later dismissed
LGTM

2019-06-26 10:39 UTC, pentaphobe submitted a review, later dismissed
Good stuff, labelling as ready

(If you update your branch, please ensure you rebase!)

2019-07-07 23:31 UTC, rokane approved these changes

2019-07-08 01:39 UTC, merged