Lab1 fibinocci: creating a new PR from a branch for Fibinocci
anz-bank/go-course pull request #40
Opened 2019-02-12 04:09 UTC by anishaNair

Fixes #

#### Changes proposed in this PR:

-
-

2019-02-12 08:29 UTC, anzdaddy requested changes

2019-02-12 08:29 UTC, anzdaddy commented on 01_fibonacci/main.go
> +}
Add a blank line between functions.

2019-02-12 08:29 UTC, anzdaddy commented on 01_fibonacci/main.go
> +	} else if x < 2 {
Idiomatic Go omits the else when the if has a return:
```go
if x <= 0 {
	return 0
}
if x < 2 {
	return x
}
```
A more pertinent issue is that fibonacci sequences aren't defined for negative numbers, so you either should fail the call or leave it undefined (letting the `x < 2` clause handle them).

2019-02-12 08:29 UTC, anzdaddy commented on 01_fibonacci/main.go
> +func fibinocci(x int) int {
Incorrect spelling

2019-02-12 08:34 UTC, anzdaddy commented
- Use the imperative form in the PR title: "create" not "creating"
- Fill in the PR description template.

2019-02-12 09:42 UTC, anzdaddy requested changes

2019-02-12 09:42 UTC, anzdaddy commented on 01_fibonacci/main.go
> +
Unnecessary blank line

2019-02-12 15:15 UTC, juliaogris reviewed
-   Click `Update branch` and locally `git pull origin lab1-fibinocci` before adding new commits.
-   Please fix up PR description according to [template](https://github.com/anz-bank/go-training/blob/master/.github/pull_request_template.md)
-   Please edit your commits to follow [recommendations](https://chris.beams.io/posts/git-commit/)
    -   Capitalize the subject line
    -   Use the imperative mood in the subject line
    -   Fold fixup commits into previous ones with `git rebase -i HASH`
I can give a hand with this if you want

2019-03-10 10:46 UTC, juliaogris commented
Hi,
There has been  no activity in the last 20 days so I will close this PR.
Feel free to open it again if you have something to add.
Thanks!
Julia

2019-03-10 10:46 UTC, closed without merging