Vadrevuslab1
anz-bank/go-course pull request #404
Opened 2019-06-16 13:27 UTC by sirigithub

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-06-17 00:30 UTC, n0npax submitted a review, later dismissed
lgmt

2019-06-18 05:55 UTC, juliaogris requested changes
Please read through the [Collected Code Review Comments](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments)
- [Fix your pr description](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#pr-description)
- [Fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages)

2019-06-18 05:55 UTC, juliaogris commented on 01_fib/sirigithub/main.go
> +	}
functionally correct. For completeness a slightly shorter version:
```go
	sign := 1
	if n < 0 {
		sign = -1
	}

	n1, n2 := 0, 1
	for j := 0; j < n*sign; j++ {
		n1, n2 = n2, n1+sign*n2
		fmt.Fprintln(out, n1)
	}
```

2019-06-18 05:55 UTC, juliaogris commented on 01_fib/sirigithub/main.go
> +
ditto

2019-06-18 05:55 UTC, juliaogris commented on 01_fib/sirigithub/main.go
> +
remove unnecessary blank line

2019-06-21 01:25 UTC, closed without merging