lab 01 updated, first commit
anz-bank/go-course pull request #440
Opened 2019-06-20 02:07 UTC by Marchitect

Fixes #439 

Review of colleague's PR #438 

#### Changes proposed in this PR:

 - updated abs() and fib() function to generate Fibonacci and Negafibonacci numbers
 - updated test cases

2019-06-23 21:54 UTC, juliaogris requested changes
Nice work!! This must have been one of the best initial PRs I've seen so far.

Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i master`.

FWIW, your solution is very close to what we came up with as the canonical solution after a bit of back and forth. In case you are interest here's ours:
```go
func fib(n int) {
	sign := 1
	if n < 0 {
		sign = -1
	}

	n1, n2 := 0, 1
	for j := 0; j < n*sign; j++ {
		n1, n2 = n2, n1+sign*n2
		fmt.Fprintln(out, n1)
	}
}
```

You could use a map rather than a slice for your table tests with the key being the test case name which can (independently of data structure) also be used as the name of the sub test.
See [Dave Cheney's post](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) for more details if you are curious (no need to fix anything, but don't hold back if you feel the urge ;) ).

2019-06-25 03:18 UTC, Marchitect commented
> Nice work!! This must have been one of the best initial PRs I've seen so far.
> 
> Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i master`.
> 
> FWIW, your solution is very close to what we came up with as the canonical solution after a bit of back and forth. In case you are interest here's ours:
> 
> ```go
> func fib(n int) {
> 	sign := 1
> 	if n < 0 {
> 		sign = -1
> 	}
> 
> 	n1, n2 := 0, 1
> 	for j := 0; j < n*sign; j++ {
> 		n1, n2 = n2, n1+sign*n2
> 		fmt.Fprintln(out, n1)
> 	}
> }
> ```
> 
> You could use a map rather than a slice for your table tests with the key being the test case name which can (independently of data structure) also be used as the name of the sub test.
> See [Dave Cheney's post](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) for more details if you are curious (no need to fix anything, but don't hold back if you feel the urge ;) ).

Thank you Julia for the feedback! :) I've updated testing, rebased the commits and made the commit msgs a bit better for this one.

2019-06-25 12:33 UTC, davidbroughsmyth commented
Your updates have been noted. LGTM.

2019-07-19 02:06 UTC, rokane commented on 01_fib/marchitect/main_test.go
> +
Little nit, but extra space here is inconsistent with the rest of the code

2019-07-19 02:11 UTC, rokane requested changes
Looking really good. I only have one suggestion and that is to provide more descriptive names for your test scenarios. All of the scenarios are of the form "normal test x" but this doesn't describe what is being tested. Think about how these tests would look for someone else running them and try to make them as straight forward as possible.

An example below:

```go
// Output with the current version
--- FAIL: Test_abs (0.08s)
    --- PASS: Test_abs/normal_test_one (0.08s)
    --- PASS: Test_abs/normal_test_two (0.08s)
    --- FAIL: Test_abs/normal_test_three (0.08s)

# vs more descriptive names
--- FAIL: Test_abs (0.08s)
    --- PASS: Test_abs/Positive_Number (0.08s)
    --- PASS: Test_abs/Negative_Number (0.08s)
    --- FAIL: Test_abs/Zero_Value (0.08s)
```

If I was modifying this code, ran the tests and saw a failure (which is described above in the example) I would prefer to see a descriptive name as it would help me understand what I could have done wrong.

 Once this is done, please ping me and I will take another look asap.

2020-09-30 04:02 UTC, anzdaddy commented
Please close merge or close.

2020-09-30 04:16 UTC, closed without merging