lab 04 updated, first commit
anz-bank/go-course pull request #451
Opened 2019-06-20 04:52 UTC by Marchitect

Fixes #448 

Review of colleague's PR #

#### Changes proposed in this PR:

- waiting for collaborator invite or permission
- added function numeronyms() and corresponding test cases

2019-06-25 04:31 UTC, patrickmarabeas commented
Looks good to me; nice accounting for special characters. The only suggestion I have is your  commit message read more like the PR message - meaningful and descriptive about what and why.

2019-06-25 06:48 UTC, Marchitect commented
> Looks good to me; nice accounting for special characters. The only suggestion I have is your commit message read more like the PR message - meaningful and descriptive about what and why.

Thank you :) I just learnt today to use the git rebase command to make changes to commit messages, will make adjustment.

2019-06-25 11:33 UTC, nicko-lee commented on 04_numeronym/marchitect/main.go
> +		length := len([]rune(val))
It's good you took into account Unicode characters. Initially when I wrote my function it worked for normal english alphabet characters. But once I put something like an emoji it gave me weird results until I converted them to a rune as well

2019-06-25 11:34 UTC, nicko-lee approved these changes

2019-07-25 02:15 UTC, juliaogris requested changes
Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH`

2019-07-25 02:15 UTC, juliaogris commented on 04_numeronym/marchitect/main.go
> +		length := len([]rune(val))
Hold on to []rune conversion as you use it again down below, e.g.:
```go
runes := []rune(val)
```
(conversion is O(N), N being the number of chars).

2019-07-25 02:15 UTC, juliaogris commented on 04_numeronym/marchitect/main.go
> +	result := make([]string, 0)
Add capacity.

2019-07-25 02:15 UTC, juliaogris commented on 04_numeronym/marchitect/main.go
> +	for _, val := range vals {
IMO it's nicer to have two functions: `numeronyms` and `nuymeronym`:
```go
func numeronyms(vals ...string) []string {
	result := make([]string, 0)
	for _, val := range vals {
                result = append(result, numeronym(val))
        }
}

func numeronyms(s string) string {
    // ...
}
```

2019-07-25 02:15 UTC, juliaogris commented on 04_numeronym/marchitect/main.go
> +
Unnecessary blank line.
No need for blank lines at beginning or end of block.
Use blank lines between type, method and function definitions and within a block for logical separation.

2020-09-30 04:13 UTC, closed without merging