lab 05 updated, first commit
anz-bank/go-course pull request #452
Opened 2019-06-20 04:54 UTC by Marchitect

Fixes #449 

Review of colleague's PR #

#### Changes proposed in this PR:

- waiting for collaborator invite or permission so can help reviewing, add labels etc. 
- added function numeronyms() and corresponding test cases

2019-06-24 11:33 UTC, joel00wood reviewed
Only thing I can really suggest is more test cases. Currently your tests confirm that the output of main() is as expected but it has no breadth of how the `String()` override behaves on your `IPAddr` data type. 

At least worth confirming behaviour for:
- Empty `IPAddr{}`
- Partially Implemented `IPAddr{1,2}`
- Fully Implemented `IPAddr{1,2,3,4}`

2019-06-25 00:59 UTC, Marchitect commented
> Only thing I can really suggest is more test cases. Currently your tests confirm that the output of main() is as expected but it has no breadth of how the `String()` override behaves on your `IPAddr` data type.
> 
> At least worth confirming behaviour for:
> 
> * Empty `IPAddr{}`
> * Partially Implemented `IPAddr{1,2}`
> * Fully Implemented `IPAddr{1,2,3,4}`

Thank you for your feedback :) kindly help check if the mentioned suggestion is now resolved?

2019-06-28 05:44 UTC, joel00wood commented
Yep looks good to me!

2019-07-25 02:39 UTC, juliaogris requested changes
Add link to your review of colleague's PR please.  
Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH`.

2019-07-25 02:39 UTC, juliaogris commented on 05_stringer/marchitect/main.go
> +// Make the IPAddr type implement fmt.Stringer to print the address as a dotted quad
Comment without context - is it for `main`?

2019-07-25 02:39 UTC, juliaogris commented on 05_stringer/marchitect/main.go
> +
Unnecessary blank line.
No need for blank lines at beginning or end of block.
Use blank lines between type, method and function definitions and within a block for logical separation.

2020-09-30 04:13 UTC, closed without merging