03
anz-bank/go-course pull request #457
Opened 2019-06-20 05:51 UTC by Marchitect

Fixes #447

Review of colleague's PR #

Changes proposed in this PR:
- waiting for collaborator invite or permission
- added function letters() and sortLetters(), test cases, issue raised by bot hopefully fixed

2019-06-24 05:20 UTC, nicko-lee approved these changes
Interesting logic of implementing letters func - didn't think of approaching it this way

2019-06-24 07:19 UTC, Marchitect commented
> Interesting logic of implementing letters func - didn't think of approaching it this way

I wanted to say I don't even understand my logic now lolz, thank you for the feedback though :)

2019-07-25 01:12 UTC, juliaogris requested changes
Please add link to your review of colleague's PR and [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH`

2019-07-25 01:12 UTC, juliaogris commented on 03_letters/marchitect/main.go
> +	// keep a list of what characters exist in the string s
what for?

2019-07-25 01:12 UTC, juliaogris commented on 03_letters/marchitect/main.go
> +		if !strings.ContainsAny(chars, string(c)) {
This is inefficient. ContainsAny is `O(n)` and so it `strings.Count(s, string(c))`, updating a map is `O(1)`.
I accept that runtime is irrelevant for the size of strings expected in this program, but it is good practise to be aware. 
```go
for _, c := range s {
    m[c]++
}
```
should do the trick

2019-07-25 01:12 UTC, juliaogris commented on 03_letters/marchitect/main.go
> +	keys := make([]int, 0)
Add the capacity to make as you know it `len(m)`.

2019-07-25 01:12 UTC, juliaogris commented on 03_letters/marchitect/main.go
> +		result = append(result, unquoted+":"+strconv.Itoa(m[rune(k)]))
```go
s := fmt.Sprintf("%c:%d", rune(k), m[rune(k)])
result = append(result, s)
```

2019-07-25 01:12 UTC, juliaogris commented on 03_letters/marchitect/main_test.go
> +		if !reflect.DeepEqual(actual, expected) {
Use testify assert.Equal to turn these three lines into a oneliner.

2020-09-30 04:13 UTC, closed without merging