Feature/lab 4 numeronym
anz-bank/go-course pull request #461
Opened 2019-06-20 06:48 UTC by starfallz

Fixes #460

Review of colleague's PR #

#### Changes proposed in this PR:

- Write a function that returns a slice of numeronyms for its input strings

2019-07-01 05:13 UTC, runnerdave approved these changes
👍

2019-07-25 02:17 UTC, juliaogris requested changes
Please add link to review of colleague's PR.
Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH`

2019-07-25 02:17 UTC, juliaogris commented on 04_numeronym/starfallz/main_test.go
> +		{"Test numeronyms with empty string to return empty string", []string{""}, []string{""}},
Please add tests with non-ascii unicode characters, e.g. emojis etc.

2019-09-18 23:42 UTC, alextmz reviewed
Some minor changes suggested

2019-09-18 23:42 UTC, alextmz commented on 04_numeronym/starfallz/main.go
> +const minNumberOfLetters = 3
Although I do like the visibility of the variable being pushed here, I'm also divided between visibility and avoiding the use of global state. I'd say go with the latter unless you know of a better guidance.

2019-09-18 23:42 UTC, alextmz commented on 04_numeronym/starfallz/main_test.go
> +				t.Errorf("Unexpected output, expected: %s, actual: %s", expected, actual)
Do not uppercase  error strings (https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

2019-09-18 23:42 UTC, alextmz commented on 04_numeronym/starfallz/main_test.go
> +}
Overall nice code! Clean and concise.

2020-09-30 04:13 UTC, closed without merging