Lab1
anz-bank/go-course pull request #511
Opened 2019-06-29 05:55 UTC by k-vikingsson

Fixes #338 

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-07-01 08:07 UTC, undrewb approved these changes
Negafib is a special case of fib. Consider refactoring to use less code.

In test you don't have tests for each function. In a simple example this doesnt matter so much but it potentially makes testing harder. Consider having tests for all functions.

Approving because it works and the logic is there.

2019-07-24 00:55 UTC, juliaogris requested changes
Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH` and read through the [Collected Code Review Comments](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments).

Adding a `switch` or `if` whose conditionals depend of the value of the loop index can be improved by pulling the special cases out of the loop so that no  tests are executed on every iteration.

Whilst your solution works, it's a bit more verbose than could be. Here our reference implementation, feel free to take it, adjust it or ignore it:
```go
func fib(n int) {
	sign := 1
	if n < 0 {
		sign = -1
	}

	n1, n2 := 0, 1
	for j := 0; j < n*sign; j++ {
		n1, n2 = n2, n1+sign*n2
		fmt.Fprintln(out, n1)
	}
}
```

2019-07-24 00:55 UTC, juliaogris commented on 01_fib/k-vikingsson/main_test.go
> +	"Basic":    {input: 7, expected: "1\n1\n2\n3\n5\n8\n13\n"},
Assignment asked for output starting at `1` not `0`

2019-07-24 00:55 UTC, juliaogris commented on 01_fib/k-vikingsson/main_test.go
> +	"Basic":    {input: 7, expected: "1\n1\n2\n3\n5\n8\n13\n"},
Assignment asked for output starting at `1` not `0`

2019-07-24 00:55 UTC, juliaogris commented on 01_fib/k-vikingsson/main.go
> +		case 1:
Pull out of loop.

2020-09-30 04:12 UTC, closed without merging