Lab5
anz-bank/go-course pull request #527
Opened 2019-07-01 11:52 UTC by hsy3418

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -Create a method to print the IP address as a dotted squad

2019-07-03 06:57 UTC, patrickmarabeas commented
Code looks good. 

You've seemed to have included your numeronym commit in this PR, you should clean up your commit history and re push.

PR needs to be updated to include the issue # it fixes; the reviewed PR #; description and formatting.

2019-07-25 02:56 UTC, juliaogris requested changes
Please fix PR description, add link to issue and review of colleague's PR.
Other than that: LGTM.

2019-08-12 01:21 UTC, juliaogris approved these changes
LGTM, just a few minor nitpicky comments - feel free to ignore.

2019-08-12 01:21 UTC, juliaogris commented on 05_stringer/hsy3418/main_test.go
> +	actual := strconv.Quote(buf.String())
remove `Quote` from both

2019-08-12 01:21 UTC, juliaogris commented on 05_stringer/hsy3418/main_test.go
> +
unnecessary blank line

2019-08-12 01:41 UTC, merged