add bubble sort main and tests
anz-bank/go-course pull request #534
Opened 2019-07-04 00:54 UTC by krnicolson

Fixes #

Review of colleague's PR #

#### Changes proposed in this PR:

## -

2019-07-04 07:28 UTC, mohitnag commented on 02_bubble/nicholsk/main.go
> +	sCopy := s
Not sure why you need a variable to make a copy over here.

2019-07-04 07:29 UTC, mohitnag commented on 02_bubble/nicholsk/main.go
> +		for i := 1; i < len(s); i++ {
why ```len(s)``` and why not ```len(sCopy)``` ?

2019-07-04 10:07 UTC, patrickmarabeas commented
Don't forget to be descriptive with your commit messages and PR. Currently your PR does not inform the reviewer what has been done, nor the issue being resolved. Also remember to use the appropriate tags.

2019-07-24 01:33 UTC, juliaogris requested changes
Please [fix commit messages](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments#commit-messages) with `git rebase -i HASH`.

Your bubble sort implementation is lacking a key parts to be called bubble sort IMO.

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main.go
> +
Unnecessary blank line.
No need for blank lines at beginning or end of block.
Use blank lines between type, method and function definitions and within a block for logical separation.

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main.go
> +	sorted := false
you don't need `sorted` and `swaps`; `swaps` alone should suffice.

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main.go
> +			sorted = true
return or break here

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main.go
> +				s[i], s[i-1] = s[i-1], s[i]
you haven't created a copy of the input slice and you are there for modifying the input.
create a test case that fails when checking that input is left unmodified and fix with `copy()`

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main.go
> +	for !sorted {
Typically bubble sort has to nested loops.
After the first iteration of the outer loop the largest element has "bubbled" up to the highest index position. 
Therefore no more comparisons with the highest index position need to be executed:

```go
	for i := len(s); i > 0; i-- {
		for j := 1; j < i; j++ {
			if s[j-1] > s[j] {
				s[j-1], s[j] = s[j], s[j-1]
			}
		}
	}
```
you can add in an early bail when nothing has been swapped ie the slice is already sorted:
```go
	for i := len(s); i > 0; i-- {
		swapped := false
		for j := 1; j < i; j++ {
			if s[j-1] > s[j] {
				s[j-1], s[j] = s[j], s[j-1]
				swapped = true
			}
		}
		if !swapped {
			// If no elements were swapped, the slice is sorted so we can stop here
			return
		}
	}
```

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main_test.go
> +	expected := make([]int, 100)
Poor naming: this is the `input` not the `expectedOutput`.

2019-07-24 01:33 UTC, juliaogris commented on 02_bubble/nicholsk/main_test.go
> +}
Add test cases for empty slice and already sorted.

2020-09-30 04:07 UTC, closed without merging