Implement lab 3 - letters
anz-bank/go-course pull request #634
Opened 2019-09-06 01:16 UTC by jimbosoft

Fixes #633

Review of colleague's PR #534

#### Changes proposed in this PR:
- Implement Lab3 letters
- Test Lab3
## -

2019-09-07 12:22 UTC, runnerdave submitted a review, later dismissed
I think is all good, being such a simple exercise, I would recommend you to implement tables for testing though, the Code Owners seem to always want that method instead of the multiple tests you did. Here is explained: [table driven testing](https://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go)

2019-09-08 11:02 UTC, camscale requested changes
mostly nitpicks which i expect you'll consistently ignore, but again, error strings have a certain requirements in Go for reasons, so at least please fix that.

+1 on sizing the slice capacity in `sortLetters`

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +	var sentence = "marry had a little lamb"
nit: "mary" is spelt with one "r".

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +func TestEmptySorter(t *testing.T) {
nitpick: blank line between functions.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +	eq := reflect.DeepEqual(res, expected)
nitpick: idiomatic Go eschews simple variables like this, instead preferring:
```
    if !reflect.DeepEqual(res, expected) {
```

Splitting your `if` over multiple lines by using an intermediate variable actually makes it less readable.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +	res := sortLetters(testMap)
A far more common name for `res` here is `actual`. You'll see that is very common in most tests.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +		t.Errorf("Result maps %v differs from expected %v", res, expected)
Go error strings should not start with capital letters: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

please fix throughout.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +
nit: I'm not going to go hard on what I see as unnecessary extra blank lines, but please be consistent. All your other functions do not have a blank line after the function signature; this one does.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +	want := "a:2\nb:1\n"
This is usually called `expected` (along with `actual`). `got` and `want` are also fine, but be consistent. In a previous test you used `expected`, so I *expect* you to also use that here.

2019-09-08 11:02 UTC, camscale commented on 03_letters/jimbotech/letter_test.go
> +		t.Errorf("expected %v, got %v", want, result)
wow. this is tortured. expected == want, got == result. just use the same name in the code as the string. i.e:
```
t.Errorf("want %v, got %v", want, got)
```
or
```
t.Errorf("expected %v, actual %v", expected, actual)
```

Either way, more consistency please.

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +	var sentence = "marry had a little lamb"
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +func TestEmptySorter(t *testing.T) {
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +	eq := reflect.DeepEqual(res, expected)
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +	res := sortLetters(testMap)
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +		t.Errorf("Result maps %v differs from expected %v", res, expected)
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +
Done

2019-09-11 07:11 UTC, jimbosoft commented on 03_letters/jimbotech/letter_test.go
> +		t.Errorf("expected %v, got %v", want, result)
Done

2019-09-15 22:36 UTC, camscale approved these changes
LGTM.

I don't know whether you noticed or not, but I can tell you that reading your tests now that you have consistent "expected" and "actual" naming, it reads quite a lot better to me. I can read it so much faster than before. It may seem like trivial nitpicking, but it does really make a difference. Thanks.

2019-10-06 11:38 UTC, merged