Lab3
anz-bank/go-course pull request #69
Opened 2019-02-13 05:02 UTC by vinilapeddireddy

Fixes #63 

#### Changes proposed in this PR:
.Implemented letter frequency
.Write a function that returns a sorted slice of strings with elements "{key}:{val}"
.Add unit test

2019-02-13 15:24 UTC, juliaogris requested changes
Very close, looking good!

Rebase onto master.
Update commits not to include any mention of fibonacci and use imperative mood (see [slides](https://gotraining.xyz/gotraining.slide#29) for rebasing help.)

2019-02-13 15:24 UTC, juliaogris commented on 03_letters/vinilapeddireddy/main.go
> +func sortLetters(m map[rune]int) []string {
Blank line between functions.

2019-02-13 15:24 UTC, juliaogris commented on 03_letters/vinilapeddireddy/main.go
> +		sortedKeys = append(sortedKeys, fmt.Sprintf("%s : %d", string(k), m[rune(k)]))
`"%s:%d"`

2019-02-13 15:24 UTC, juliaogris commented on 03_letters/vinilapeddireddy/main_test.go
> +
Remove blank line.

2019-02-14 03:12 UTC, vinilapeddireddy commented on 03_letters/vinilapeddireddy/main.go
> +func sortLetters(m map[rune]int) []string {
Done

2019-02-14 03:13 UTC, vinilapeddireddy commented on 03_letters/vinilapeddireddy/main.go
> +		sortedKeys = append(sortedKeys, fmt.Sprintf("%s : %d", string(k), m[rune(k)]))
Done

2019-02-14 03:13 UTC, vinilapeddireddy commented on 03_letters/vinilapeddireddy/main_test.go
> +
Done

2019-02-14 04:17 UTC, juliaogris approved these changes
LGTM 😻

2019-02-14 04:18 UTC, juliaogris commented
Once you have approval you should be able to just click the `Update branch` button and without further reapproval merge.

2019-02-14 04:32 UTC, merged