Lab03/letters
anz-bank/go-course pull request #74
Opened 2019-02-13 08:12 UTC by SandhyaSMani

Fixes #

#### Changes proposed in this PR:
Implementing frequency of letters in ascending order

2019-02-13 08:34 UTC, mohankrishna commented
Please remove the fibonacci series related files.

2019-02-13 08:42 UTC, juliaogris commented
Please fix broken build and `Update branch`

2019-02-13 09:45 UTC, SandhyaSMani commented on 01_fib/01_fib.go
> +func main() {
code doesn't exist because I removed this unwanted file

2019-02-13 09:46 UTC, SandhyaSMani commented on 01_fib/01_fib.go
> +func fib(n int) int {
code doesn't exist because I removed this unwanted file

2019-02-13 09:46 UTC, SandhyaSMani commented on 01_fib/01_fib.go
> +var out io.Writer = os.Stdout
code doesn't exist because I removed this unwanted file

2019-02-13 15:18 UTC, juliaogris requested changes
Please edit your commits to follow [recommendations](https://chris.beams.io/posts/git-commit/)
-   Use the imperative mood in the subject line (ie `Change` instead of `Changing`, `Include` instead of `Included`)
-  There should be no commits referring to fibonacci in this PR
-   Fold fixup commits into previous ones with `git rebase -i HASH` (make backup branch first)
    See [slides](https://gotraining.xyz/gotraining.slide#29).

2019-02-13 15:18 UTC, juliaogris commented on 03_letters/SandhyaSMani/03_letters.go
> +		strArray = append(strArray, fmt.Sprintf("%s : %d", string(key), m[rune(key)]))
Request format was `"%s:%d"`

2019-02-13 15:18 UTC, juliaogris commented on 03_letters/SandhyaSMani/03_letters_test.go
> +	expected := map[rune]int{97: 2, 98: 1}
Add more test cases with [table driven tests](https://github.com/golang/go/wiki/TableDrivenTests).

2019-02-13 15:18 UTC, juliaogris commented on 03_letters/SandhyaSMani/03_letters_test.go
> +	actual := sortLetters(map[rune]int{97: 2, 98: 1})
Add more test cases with [table driven tests](https://github.com/golang/go/wiki/TableDrivenTests).

2019-03-10 10:44 UTC, juliaogris commented
Hi,
There has been  no activity in the last 20 days so I will close this PR.
Feel free to open it again if you have something to add.
Thanks!
Julia

2019-03-10 10:44 UTC, closed without merging